"use client";

// import type { Metadata } from "next";
// import "jsvectormap/dist/jsvectormap.css";
import { Inter } from "next/font/google";
import "./globals.css";
import CommonLayout from "@/layouts/common-layout";
import { GeneralStoreProvider } from "@/providers/GeneralStoreProvider";
import { ClerkProvider } from "@clerk/nextjs";
import Loader from "@/components/common/Loader";
import React, { useEffect, useState } from "react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [sidebarOpen, setSidebarOpen] = useState(false);
  const [loading, setLoading] = useState<boolean>(true);

  // const pathname = usePathname();

  useEffect(() => {
    setTimeout(() => setLoading(false), 1000);
  }, []);

  return (
    <ClerkProvider
      publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
    >
      <html lang="en">
        {/* <head>
        <link href="https://cdn.jsdelivr.net/npm/flowbite@3.0.0/dist/flowbite.min.css" rel="stylesheet" />

        </head> */}
        <body className={inter.className}>
          <GeneralStoreProvider>
            <div className="dark:bg-boxdark-2 dark:text-bodydark">
              {loading ? <Loader /> : children}
            </div>
            {/* <CommonLayout>{loading ? <Loader /> : children}</CommonLayout> */}
          </GeneralStoreProvider>
          {/* <script src="https://cdn.jsdelivr.net/npm/flowbite@3.0.0/dist/flowbite.min.js"></script> */}
        </body>
      </html>
    </ClerkProvider>
  );
}
